In [77]:
import pandas as pd

columns_to_keep = ['careerLevel.value', 'clearance.value', 'clearanceText', 'companyName', 'description_text', 'id', 'jobIndustry.value',
 'jobName', 'jobType.value', 'locations[0].city', 'locations[0].country', 'locations[0].state', 'locations[0].type',
 'locations[0].zip', 'locations[1].city', 'locations[1].country', 'locations[1].state', 'locations[1].type',
 'locations[1].zip', 'locations[2].city', 'locations[2].country', 'locations[2].state', 'locations[2].type',
 'locations[2].zip', 'locations[3].city', 'locations[3].country', 'locations[3].state', 'locations[3].type',
 'locations[3].zip', 'locations[4].city', 'locations[4].country', 'locations[4].state', 'locations[4].type',
 'locations[4].zip', 'polygraph.value', 'postedAt', 'remote', 'salary.value', 'salaryComments', 'travel.value'
 ]

jobs = pd.read_csv('detailed_jobs.csv', low_memory=False)
jobs_filtered = jobs[columns_to_keep]
jobs_filtered.head()

,careerLevel.value,clearance.value,clearanceText,companyName,description_text,id,jobIndustry.value,jobName,jobType.value,locations[0].city,...,locations[4].country,locations[4].state,locations[4].type,locations[4].zip,polygraph.value,postedAt,remote,salary.value,salaryComments,travel.value
0,NaN,Public Trust,NaN,AT&T Government Solutions,Job Description:\nThis position requires offic...,8454829,NaN,Associate Director-Business Operations (Govern...,Employee,Chantilly,...,NaN,NaN,NaN,NaN,Unspecified,2025-07-25T20:02:27-05:00,False,Unspecified,NaN,NaN
1,NaN,DoE Q or L,NaN,GAP Solutions Inc,Position Objective: \n Provide services as a S...,8454828,NaN,Scientist,Employee,Gaithersburg,...,NaN,NaN,NaN,NaN,Unspecified,2025-07-25T20:02:09-05:00,False,Unspecified,NaN,NaN
2,NaN,Top Secret,NaN,"Watermark Risk Management International, LLC",Come make your mark with Watermark! \n \n ðŸŽ– \n...,8454827,Logistics,Budget and Procurement Analyst - Entry,Employee,washington dc,...,NaN,NaN,NaN,NaN,Unspecified,2025-07-25T20:02:00-05:00,False,Unspecified,NaN,NaN
3,NaN,Public Trust,NaN,"Ryan Consulting Group, Inc",Shift: Standard; On-site\nPay Range: Based on ...,8454826,IT - Security,Insider Threat Analyst (Active Secret Security...,Employee,Smyrna,...,NaN,NaN,NaN,NaN,Unspecified,2025-07-25T20:01:55-05:00,False,Unspecified,NaN,NaN
4,Senior Level Career (10+ yrs experience),Top Secret,NaN,10x National Security,Overview\n\n10x National Security is seeking a...,8454825,IT - Software,ServiceNow Developer,Employee,Hanover,...,NaN,NaN,NaN,NaN,NaN,2025-07-25T19:43:43-05:00,False,"$150,000 and above",NaN,Occasional travel

In [78]:
columns_rename = {'careerLevel.value': 'career_level', 'clearance.value': 'clearance', 'clearanceText': 'clearance_text', 'companyName': 'company_name',
                  'jobIndustry.value': 'job_industry', 'jobName': 'job_name', 'locations[0].city': 'city1', 'locations[0].country': 'country1',
                  'locations[0].state': 'state1', 'locations[0].type': 'location_type1', 'locations[0].zip': 'zip1', 'locations[1].city': 'city2', 
                  'locations[1].country': 'country2', 'locations[1].state': 'state2', 'locations[1].type': 'location_type2', 'locations[1].zip': 'zip2', 
                  'locations[2].city': 'city3', 'locations[2].country': 'country3', 'locations[2].state': 'state3', 'locations[2].type': 'location_type3', 
                  'locations[2].zip': 'zip3', 'locations[3].city': 'city4', 'locations[3].country': 'country4', 'locations[3].state': 'state4', 
                  'locations[3].type': 'location_type4', 'locations[3].zip': 'zip4', 'locations[4].city': 'city5', 'locations[4].country': 'country5',
                  'locations[4].state': 'state5', 'locations[4].type': 'location_type5', 'locations[4].zip': 'zip5', 'polygraph.value': 'polygraph',
                  'postedAt': 'posted_at', 'salary.value': 'salary', 'salaryComments': 'salary_comments', 'travel.value': 'travel'}

jobs_renamed = jobs_filtered.rename(columns_rename, axis=1)
jobs_renamed.head()

,career_level,clearance,clearance_text,company_name,description_text,id,job_industry,job_name,jobType.value,city1,...,country5,state5,location_type5,zip5,polygraph,posted_at,remote,salary,salary_comments,travel
0,NaN,Public Trust,NaN,AT&T Government Solutions,Job Description:\nThis position requires offic...,8454829,NaN,Associate Director-Business Operations (Govern...,Employee,Chantilly,...,NaN,NaN,NaN,NaN,Unspecified,2025-07-25T20:02:27-05:00,False,Unspecified,NaN,NaN
1,NaN,DoE Q or L,NaN,GAP Solutions Inc,Position Objective: \n Provide services as a S...,8454828,NaN,Scientist,Employee,Gaithersburg,...,NaN,NaN,NaN,NaN,Unspecified,2025-07-25T20:02:09-05:00,False,Unspecified,NaN,NaN
2,NaN,Top Secret,NaN,"Watermark Risk Management International, LLC",Come make your mark with Watermark! \n \n ðŸŽ– \n...,8454827,Logistics,Budget and Procurement Analyst - Entry,Employee,washington dc,...,NaN,NaN,NaN,NaN,Unspecified,2025-07-25T20:02:00-05:00,False,Unspecified,NaN,NaN
3,NaN,Public Trust,NaN,"Ryan Consulting Group, Inc",Shift: Standard; On-site\nPay Range: Based on ...,8454826,IT - Security,Insider Threat Analyst (Active Secret Security...,Employee,Smyrna,...,NaN,NaN,NaN,NaN,Unspecified,2025-07-25T20:01:55-05:00,False,Unspecified,NaN,NaN
4,Senior Level Career (10+ yrs experience),Top Secret,NaN,10x National Security,Overview\n\n10x National Security is seeking a...,8454825,IT - Software,ServiceNow Developer,Employee,Hanover,...,NaN,NaN,NaN,NaN,NaN,2025-07-25T19:43:43-05:00,False,"$150,000 and above",NaN,Occasional travel

In [94]:
import pandas as pd
import numpy as np
import re

def parse_salary(s):
    if pd.isna(s):
        return np.nan, np.nan

    s = str(s).lower().strip()

    # Skip hourly, daily, weekly
    if any(time_unit in s for time_unit in ['hour', '/hr', '/hour', 'per hour', 'weekly', 'per week', 'a week', 'daily', 'per day']):
        return np.nan, np.nan

    is_monthly = 'per month' in s or 'monthly' in s

    # Extract monetary numbers with optional $ or commas
    raw_nums = re.findall(r'\$?\d[\d,\.]*', s)
    clean_nums = []

    for num in raw_nums:
        num_clean = num.replace('$', '').replace(',', '')
        try:
            val = float(num_clean)
            if is_monthly:
                val *= 12
            if 1_000 <= val <= 1_000_000:
                clean_nums.append(val)
        except ValueError:
            continue

    clean_nums = sorted(set(clean_nums))

    if len(clean_nums) == 0:
        return np.nan, np.nan
    elif len(clean_nums) == 1:
        return clean_nums[0], np.nan
    else:
        return clean_nums[0], clean_nums[-1]

In [95]:
jobs_renamed[['salary_lower', 'salary_upper']] = jobs_renamed['salary_comments'].apply(lambda x: pd.Series(parse_salary(x)))
jobs_renamed.head()

,career_level,clearance,clearance_text,company_name,description_text,id,job_industry,job_name,jobType.value,city1,...,location_type5,zip5,polygraph,posted_at,remote,salary,salary_comments,travel,salary_lower,salary_upper
0,NaN,Public Trust,NaN,AT&T Government Solutions,Job Description:\nThis position requires offic...,8454829,NaN,Associate Director-Business Operations (Govern...,Employee,Chantilly,...,NaN,NaN,Unspecified,2025-07-25T20:02:27-05:00,False,Unspecified,NaN,NaN,NaN,NaN
1,NaN,DoE Q or L,NaN,GAP Solutions Inc,Position Objective: \n Provide services as a S...,8454828,NaN,Scientist,Employee,Gaithersburg,...,NaN,NaN,Unspecified,2025-07-25T20:02:09-05:00,False,Unspecified,NaN,NaN,NaN,NaN
2,NaN,Top Secret,NaN,"Watermark Risk Management International, LLC",Come make your mark with Watermark! \n \n ðŸŽ– \n...,8454827,Logistics,Budget and Procurement Analyst - Entry,Employee,washington dc,...,NaN,NaN,Unspecified,2025-07-25T20:02:00-05:00,False,Unspecified,NaN,NaN,NaN,NaN
3,NaN,Public Trust,NaN,"Ryan Consulting Group, Inc",Shift: Standard; On-site\nPay Range: Based on ...,8454826,IT - Security,Insider Threat Analyst (Active Secret Security...,Employee,Smyrna,...,NaN,NaN,Unspecified,2025-07-25T20:01:55-05:00,False,Unspecified,NaN,NaN,NaN,NaN
4,Senior Level Career (10+ yrs experience),Top Secret,NaN,10x National Security,Overview\n\n10x National Security is seeking a...,8454825,IT - Software,ServiceNow Developer,Employee,Hanover,...,NaN,NaN,NaN,2025-07-25T19:43:43-05:00,False,"$150,000 and above",NaN,Occasional travel,NaN,NaN

In [96]:
jobs_renamed[~jobs_renamed['salary_lower'].isna()].sort_values('salary_lower')

,career_level,clearance,clearance_text,company_name,description_text,id,job_industry,job_name,jobType.value,city1,...,location_type5,zip5,polygraph,posted_at,remote,salary,salary_comments,travel,salary_lower,salary_upper
13774,NaN,DoE Q or L,NaN,Lawrence Livermore National Laboratory,Company Description\n \nJoin us and make YOUR ...,8433146,NaN,CGSR Graduate Research Associate - Spring 2026,Employee,Livermore,...,NaN,NaN,Unspecified,2025-07-25T20:06:40-05:00,False,Unspecified,"USD 6,620.00 - 8,040.00",NaN,6620.0,8040.0
41718,Student (undergraduate/graduate),Unspecified,Candidates will be working for the EPA and wil...,Elite Government Strategy,"Summary: \n\nThe Date Entry Clerk creates, rec...",8252312,Business - Support,Data Entry (100% remote) pays $16.88hr,Employee,NaN,...,NaN,NaN,NaN,2025-07-24T08:34:24-05:00,True,NaN,"$35,000",No Traveling,35000.0,NaN
30379,NaN,Unspecified,Must be able to obtain and maintain a Secret C...,"Caribou Thunder, LLC",Human Resources Specialist (Mid)\n\n\n\nMid-Le...,8376259,Business - HR,Human Resources Specialist (Mid),NaN,Colorado Springs,...,NaN,NaN,NaN,2025-07-25T16:25:36-05:00,False,"$50,000 - $60,000","$40,000",NaN,40000.0,NaN
46574,Early Career (2+ yrs experience),Secret,NaN,PlanIT Group LLC,Request-ID:\t\t16459-1 \n\nWork Location:\t Fo...,8075853,Construction/Facilities,Facility Operations Analyst,Contractor/Consultant,Fort Liberty,...,NaN,NaN,NaN,2025-07-25T13:44:24-05:00,False,NaN,"$40,000",NaN,40000.0,NaN
3878,Entry Level (less than 2 yrs experience),Unspecified,NaN,Kforce Federal Solutions,Kforce has a client that is seeking a Security...,8450652,NaN,Security Receptionist,Employee,Sierra Vista,...,NaN,NaN,Unspecified,2025-07-25T14:53:43-05:00,False,Unspecified,"$41,000 - $43,000 annually",NaN,41000.0,43000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
38778,NaN,DoE Q or L,NaN,Lawrence Livermore National Laboratory,Company Description\n \nJoin us and make YOUR ...,8307052,NaN,Associate Deputy Director for Science and Tech...,Employee,Livermore,...,NaN,NaN,Unspecified,2025-07-25T20:06:53-05:00,False,Unspecified,"USD 386,730.00 - 496,620.00 per year",NaN,386730.0,496620.0
46947,Mid Level Career (5+ yrs experience),Unspecified,NaN,OMW Consulting,Software Engineer - Target tracking team\n\n\n...,8038289,IT - Software,Software Engineer - Tracking Team,Employee,Washington Dc Brm,...,NaN,NaN,NaN,2025-07-25T14:51:31-05:00,False,NaN,"$400,000",Occasional travel,400000.0,NaN
47174,Mid Level Career (5+ yrs experience),Secret,Minimum secret needed the higher the better,OMW Consulting,Software Engineer - Forward Deployed - K8S\n\n...,8003424,IT - Software,Software Engineer - K8s,Employee,Washington Dc Brm,...,NaN,NaN,NaN,2025-07-25T14:51:31-05:00,False,NaN,"$400,000",NaN,400000.0,NaN
44578,Mid Level Career (5+ yrs experience),Top Secret/SCI,NaN,"Capitol Consulting Networks, Inc.","The Role\n\n\n\nIn this role, youâ€™ll help mark...",8163083,Business - Sales,Fed IC Account Executive - Big Data,Employee,NaN,...,NaN,NaN,CI Polygraph,2025-06-30T17:28:09-05:00,True,"$150,000 and above","$450,000",Occasional travel,450000.0,NaN
19038,Senior Level Career (10+ yrs experience),Top Secret/SCI,Has to be an active TS/SCI,OMW Consulting,Founding Forward Deployed Engineer \n\nLocatio...,8418595,IT - Data Science,Forward Deployed Engineer - up to $500k comp,Employee,Berkeley,...,NaN,NaN,NaN,2025-07-25T14:51:31-05:00,False,NaN,"$500,000",NaN,500000.0,NaN

In [106]:
jobs_renamed[jobs_renamed['company_name'].str.lower().str.contains('northrop')]

,career_level,clearance,clearance_text,company_name,description_text,id,job_industry,job_name,jobType.value,city1,...,location_type5,zip5,polygraph,posted_at,remote,salary,salary_comments,travel,salary_lower,salary_upper
77,NaN,Top Secret,NaN,Northrop Grumman,AUSTRALIAN CITIZENSHIP REQUIRED FOR THIS POSIT...,8454734,Aerospace and Aviation,Aircraft Maintenance Engineer - Avionics,Employee,Tindal,...,NaN,NaN,Unspecified,2025-07-25T16:57:33-05:00,False,Unspecified,NaN,NaN,NaN,NaN
78,NaN,Secret,NaN,Northrop Grumman,RELOCATION ASSISTANCE: Relocation assistance m...,8454733,NaN,Plasma Enhanced CVD Semiconductor Process Engi...,Employee,Linthicum Heights,...,NaN,NaN,Unspecified,2025-07-25T16:57:33-05:00,False,Unspecified,NaN,NaN,NaN,NaN
79,NaN,Secret,NaN,Northrop Grumman,RELOCATION ASSISTANCE: Relocation assistance m...,8454732,Management,Principal Program Planning and Scheduling Analyst,Employee,Melbourne,...,NaN,NaN,Unspecified,2025-07-25T16:57:33-05:00,False,Unspecified,NaN,NaN,NaN,NaN
80,NaN,Secret,NaN,Northrop Grumman,RELOCATION ASSISTANCE: Relocation assistance m...,8454731,IT - Security,Sentinel - Staff Security Software Engineer - ...,Employee,Huntsville,...,NaN,NaN,Unspecified,2025-07-25T16:57:33-05:00,False,Unspecified,NaN,NaN,NaN,NaN
83,NaN,Secret,NaN,Northrop Grumman,RELOCATION ASSISTANCE: Relocation assistance m...,8454728,Engineering - Electrical,Sentinel Principal Electrical Engineer/ Sr Pri...,Employee,Huntsville,...,NaN,NaN,Unspecified,2025-07-25T16:57:33-05:00,False,Unspecified,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
44743,Early Career (2+ yrs experience),Secret,NaN,Northrop Grumman,The Sentinel Mission Defense Team (MDT) is see...,8159127,Engineering - Systems,System-Theoretic Process Analysis (STPA) Engineer,Employee,Colorado Springs,...,NaN,NaN,NaN,2025-07-25T16:57:33-05:00,False,"$100,000 - $125,000",NaN,NaN,NaN,NaN
44744,Senior Level Career (10+ yrs experience),Secret,NaN,Northrop Grumman,Northrop Grumman Defense Systems is seeking to...,8159124,Engineering - Electrical,Senior TEMPEST Engineer,Employee,Huntsville,...,NaN,NaN,NaN,2025-07-25T16:57:33-05:00,False,"$150,000 and above",NaN,NaN,NaN,NaN
46761,NaN,Secret,NaN,Northrop Grumman,RELOCATION ASSISTANCE: Relocation assistance m...,8058830,NaN,U109 Semi-conductor Equipment Technician C - 1...,NaN,Linthicum Heights,...,NaN,NaN,NaN,2025-07-25T16:57:33-05:00,False,Unspecified,NaN,NaN,NaN,NaN
46762,NaN,Secret,NaN,Northrop Grumman,RELOCATION ASSISTANCE: Relocation assistance m...,8058143,NaN,U109 Semi-conductor Equipment Technician C - 1...,NaN,Linthicum Heights,...,NaN,NaN,Unspecified,2025-07-25T16:57:33-05:00,False,Unspecified,NaN,NaN,NaN,NaN
46865,Mid Level Career (5+ yrs experience),Secret,NaN,Northrop Grumman,"At Northrop Grumman, our employees have incred...",8048594,Aerospace and Aviation,E3 Engineer,Employee,Roy,...,NaN,NaN,NaN,2025-07-25T16:57:33-05:00,False,NaN,NaN,Occasional travel,NaN,NaN